<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Title>Microsoft Exchange Managed API - .NET7</Title>
    <Authors>SmarterTools</Authors>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <Version>3.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices" Version="7.0.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="7.0.1" />
  </ItemGroup>

</Project>
